[package]
name = "algotrading"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.6"
chrono = "0.4.38"
mongodb = "3.1.0"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.12"
uuid = "1.10.0"
